### ISSUE TITLE
Icon for External links 

### ISSUE THREAD

**Issue by miakobchuk** [hlxsites/24petwatch#100]
The external link icon should be the same color as the text next to it.

**Comment by mikeweis** [comment]
Pages with external links include:
* https://www.24petwatch.com/about-us
* https://www.24petwatch.com/pet-insurance
  * https://www.24petwatch.com/ca/pet-insurance
* https://www.24petwatch.com/underwriter
  * https://www.24petwatch.com/ca/underwriter
* https://www.24petwatch.com/lost-pet-protection
  * https://www.24petwatch.com/ca/lost-pet-protection
* https://www.24petwatch.com/lost-pet-protection/pet-recovery-tips
* https://www.24petwatch.com/lost-pet-protection/why-microchip
* https://www.24petwatch.com/lost-pet-protection/faq
* https://www.24petwatch.com/lost-pet-protection/membership
  *  https://www.24petwatch.com/ca/lost-pet-protection/membership
* https://www.24petwatch.com/lost-pet-protection/membership-benefits

**Comment by mikeweis** [comment]
PR: https://github.com/hlxsites/24petwatch/pull/127
