### ISSUE TITLE
Icon for PDF links

### ISSUE THREAD

**Issue by miakobchuk** [hlxsites/24petwatch#101]
Add PDF icon before links that serve a PDF file for downloading

**Comment by mikeweis** [comment]
Probably can generalize the PDF styling added in PR https://github.com/hlxsites/24petwatch/pull/80

**Comment by mikeweis** [comment]
Pages with PDF links include:
* https://www.24petwatch.com/pet-insurance
* https://www.24petwatch.com/lost-pet-protection/membership
* https://www.24petwatch.com/ca/lost-pet-protection/membership
* https://www.24petwatch.com/lost-pet-protection/transfer-microchip-registration
* https://www.24petwatch.com/privacy-policy
* https://www.24petwatch.com/ca/privacy-policy

**Comment by mikeweis** [comment]
PR: https://github.com/hlxsites/24petwatch/pull/126
