### ISSUE TITLE
Enable CA flag in nav menu

### ISSUE THREAD

**Issue by miakobchuk** [hlxsites/24petwatch#147]
In CA page, US flag is seen at the top

In CA page, Nav menu  Membership -> contains annual protection plan which should not be available in CA site.

**Comment by mikeweis** [comment]
☝️ I believe the *conservative* fix will be to append the following snippet to the `isCanada()` method:
```
|| startsWith('/drafts/develop/ca/')
```
* the `isCanada()` method controls wether the US or Canadian flag is shown
* the `isCanada()` method controls which navigation dropdown is shown
  * the US navigation **will** show the annual protection plan is available
  * the CA navigation will **not** show the annual protection plan

**Comment by mikeweis** [comment]
@miakobchuk solved this more elegantly: Maksym moved the Word documents to their correct / final locations.  This allows our `isCanada()` helper to "see" Canada versus the United States.
![oh-Canada](https://github.com/user-attachments/assets/bd89fc79-daf9-412d-a935-67ce28c7cb79)
