### ISSUE TITLE
Implement the footer

### ISSUE THREAD

**Issue by ekremney** [hlxsites/24petwatch#4]

**Comment by dzehnder** [comment]
Progress:

- [x] Styling the footer columns for mobile
- [x] Styling the footer columns for desktop
- [ ] Make columns collapsible in mobile
- [ ] Be able to nest columns (e.g Login and About)
- [ ] Styling for footer logo
- [ ] Styling for footer navigation
- [ ] Styling for Licence note

**Comment by dzehnder** [comment]
I moved the external Links in the footer to a new issue due to time constraints #25
