### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by mikeweis** [hlxsites/24petwatch#85]
- https://www.24petwatch.com/lost-pet-protection/faq
- https://www.24petwatch.com/ca/lost-pet-protection/faq

Notes:
* the text under the topic "What is included in the Lifetime Protection Membership" is different between USA and Canada.
  * there *might* be other topics that have different text
* this page structure lends itself to the `accordion` block

**Comment by miakobchuk** [comment]
https://github.com/hlxsites/24petwatch/pull/89
